from __future__ import annotations
from pathlib import Path
from urllib.parse import urlparse, unquote
import os, re, uuid
import httpx

class DownloadError(Exception):
    pass


ALLOWED_DOWNLOAD_HOSTS = frozenset({
    'github.com',
    'www.github.com',
    'raw.githubusercontent.com',
    'objects.githubusercontent.com',
    'codeload.github.com',
})


def _allowed_download_host(host: str) -> bool:
    host = (host or '').lower().split(':', 1)[0]
    if host in ALLOWED_DOWNLOAD_HOSTS:
        return True
    return host.endswith('.githubusercontent.com')

def normalize_github_file_url(url: str) -> dict:
    url = url.strip()
    parsed = urlparse(url)
    host = parsed.netloc.lower()
    path = parsed.path

    if host == 'raw.githubusercontent.com':
        parts = path.strip('/').split('/')
        if len(parts) < 4:
            raise DownloadError('Invalid raw.githubusercontent.com URL')
        owner, repo, branch = parts[0], parts[1], parts[2]
        file_path = '/'.join(parts[3:])
        return {
            'source_type': 'github_raw',
            'owner': owner,
            'repo': repo,
            'branch': branch,
            'path': file_path,
            'download_url': url,
            'display_url': url,
        }

    if host == 'github.com':
        parts = path.strip('/').split('/')
        if len(parts) >= 5 and parts[2] == 'blob':
            owner, repo, branch = parts[0], parts[1], parts[3]
            file_path = '/'.join(parts[4:])
            raw = f'https://raw.githubusercontent.com/{owner}/{repo}/{branch}/{file_path}'
            return {
                'source_type': 'github_blob',
                'owner': owner,
                'repo': repo,
                'branch': branch,
                'path': file_path,
                'download_url': raw,
                'display_url': url,
            }
        # New GitHub raw format generated by github.com:
        # https://github.com/owner/repo/raw/refs/heads/main/path/file.zip
        if len(parts) >= 7 and parts[2] == 'raw' and parts[3] == 'refs' and parts[4] == 'heads':
            owner, repo, branch = parts[0], parts[1], parts[5]
            file_path = '/'.join(parts[6:])
            raw = f'https://raw.githubusercontent.com/{owner}/{repo}/{branch}/{file_path}'
            return {
                'source_type': 'github_raw_refs_heads',
                'owner': owner,
                'repo': repo,
                'branch': branch,
                'path': file_path,
                'download_url': raw,
                'display_url': url,
            }
        # Legacy/direct GitHub raw URL format:
        # https://github.com/owner/repo/raw/main/path/file.zip
        if len(parts) >= 5 and parts[2] == 'raw':
            owner, repo, branch = parts[0], parts[1], parts[3]
            file_path = '/'.join(parts[4:])
            raw = f'https://raw.githubusercontent.com/{owner}/{repo}/{branch}/{file_path}'
            return {
                'source_type': 'github_raw_path',
                'owner': owner,
                'repo': repo,
                'branch': branch,
                'path': file_path,
                'download_url': raw,
                'display_url': url,
            }
        # release asset / other direct GitHub URL: let GitHub redirect and download
        if 'releases/download' in path:
            owner = parts[0] if len(parts) > 0 else ''
            repo = parts[1] if len(parts) > 1 else ''
            file_path = parts[-1] if parts else 'download.bin'
            return {
                'source_type': 'github_release_asset',
                'owner': owner,
                'repo': repo,
                'branch': None,
                'path': file_path,
                'download_url': url,
                'display_url': url,
            }

    raise DownloadError('Only GitHub blob, raw.githubusercontent, GitHub raw, raw/refs/heads, and GitHub release asset URLs are supported in v1.1')

def safe_filename(name: str) -> str:
    name = unquote(name.split('/')[-1] or 'sample.bin')
    return re.sub(r'[^A-Za-z0-9._-]+', '_', name)[:180] or 'sample.bin'

async def download_file(url: str, out_dir: str | Path = 'downloads', max_bytes: int | None = None) -> dict:
    meta = normalize_github_file_url(url)
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    max_bytes = max_bytes or int(os.getenv('MAX_DOWNLOAD_BYTES', '50000000'))
    filename = safe_filename(meta.get('path') or 'sample.bin')
    out_path = out_dir / f'{uuid.uuid4().hex}_{filename}'

    downloaded = 0
    async with httpx.AsyncClient(follow_redirects=True, timeout=45) as client:
        async with client.stream('GET', meta['download_url']) as resp:
            final_host = urlparse(str(resp.url)).netloc
            if not _allowed_download_host(final_host):
                raise DownloadError(f'Download blocked: redirect left GitHub ({final_host})')
            if resp.status_code >= 400:
                raise DownloadError(f'Download failed: HTTP {resp.status_code}')
            with out_path.open('wb') as f:
                async for chunk in resp.aiter_bytes(1024 * 256):
                    downloaded += len(chunk)
                    if downloaded > max_bytes:
                        try:
                            out_path.unlink(missing_ok=True)
                        except Exception:
                            pass
                        raise DownloadError(f'File exceeds safety limit of {max_bytes} bytes')
                    f.write(chunk)
    meta.update({'local_path': str(out_path), 'filename': filename, 'downloaded_bytes': downloaded})
    return meta
