from __future__ import annotations

import re
from typing import Callable

# Extended capability definitions merged into semantic.CAPABILITY_DEFS
EXTENDED_CAPABILITY_DEFS: dict[str, str] = {
    'cobalt_strike': 'Cobalt Strike / beacon-style markers',
    'sliver_c2': 'Sliver C2 framework markers',
    'havoc_c2': 'Havoc C2 framework markers',
    'asyncrat_marker': 'AsyncRAT / remote access trojan markers',
    'njrat_marker': 'NjRAT / Bladabindi markers',
    'quasar_marker': 'Quasar RAT markers',
    'remcos_marker': 'Remcos RAT markers',
    'redline_stealer': 'RedLine stealer markers',
    'impacket_tool': 'Impacket / secretsdump-style tooling',
    'bloodhound_ad': 'BloodHound / AD graph enumeration',
    'mimikatz_tool': 'Mimikatz / sekurlsa credential dumping',
    'webshell_php': 'PHP web shell eval patterns',
    'webshell_asp': 'ASP/JSP web shell patterns',
    'amsi_bypass': 'AMSI bypass or patch patterns',
    'uac_bypass': 'UAC bypass / elevation bypass',
    'lolbin_certutil': 'Certutil decode/download abuse',
    'lolbin_msbuild': 'MSBuild inline task abuse',
    'lolbin_regsvr32': 'Regsvr32 squiblydoo pattern',
    'lolbin_rundll32': 'Rundll32 suspicious invocation',
    'lolbin_mshta': 'MSHTA remote script launcher',
    'macro_office': 'Office macro / VBA auto-exec',
    'hta_execution': 'HTML Application (HTA) launcher',
    'crypto_miner': 'Cryptocurrency miner markers',
    'stratum_mining': 'Stratum mining pool protocol',
    'browser_stealer': 'Browser credential/cookie theft',
    'cookie_stealer': 'Browser cookie/session theft',
    'discord_stealer': 'Discord token theft',
    'wallet_stealer': 'Cryptocurrency wallet theft',
    'password_spray': 'Password spraying / auth brute',
    'ssh_brute': 'SSH brute-force patterns',
    'kerberos_attack': 'Kerberos attack (roast/ticket)',
    'ldap_enumeration': 'LDAP / Active Directory enumeration',
    'dcom_lateral': 'DCOM lateral movement',
    'wmi_lateral': 'WMI remote execution',
    'psexec_lateral': 'PsExec / SMB lateral movement',
    'sandbox_evasion': 'Sandbox or VM evasion checks',
    'vm_detection': 'Virtual machine detection',
    'dns_exfil': 'DNS tunneling / exfiltration',
    'icmp_tunnel': 'ICMP tunneling',
    'tor_network': 'Tor / onion routing usage',
    'proxy_socks': 'SOCKS/proxy pivot setup',
    'phishing_html': 'Credential phishing page HTML',
    'sql_injection': 'SQL injection probe payloads',
    'xss_probe': 'Cross-site scripting probe',
    'container_escape': 'Container escape patterns',
    'kube_exfil': 'Kubernetes API abuse',
    'aws_exfil': 'AWS credential / metadata abuse',
    'azure_exfil': 'Azure credential abuse',
    'gcp_exfil': 'GCP credential abuse',
    'ransomware_vss': 'Shadow copy / VSS deletion (ransomware)',
    'reflective_dll': 'Reflective DLL loading',
    'donut_loader': 'Donut / shellcode loader markers',
    'nuclei_scanner': 'Nuclei vulnerability scanner',
    'ffuf_fuzzer': 'Web fuzzer (ffuf/gobuster)',
    'hydra_brute': 'THC-Hydra brute-force tool',
    'hashcat_helper': 'Hash cracking utility references',
    'responder_poison': 'Responder LLMNR/NBT-NS poisoning',
    'bettercap_attack': 'Bettercap MITM attack',
    'sqlmap_tool': 'SQLMap automated SQLi',
    'beef_hook': 'BeEF browser exploitation hook',
    'empire_agent': 'PowerShell Empire agent',
    'covenant_grpc': 'Covenant C2 grcp markers',
    'persistence_wmi': 'WMI event subscription persistence',
    'persistence_schtask': 'Scheduled task persistence',
    'persistence_startup': 'Startup folder / Run key persistence',
    'defense_disable': 'Disable AV/firewall/defender',
    'log_clearing': 'Clear event logs',
    'timestomp': 'File timestamp manipulation',
    'process_hollow': 'Process hollowing indicators',
    'api_unhook': 'NTDLL/API unhooking',
    'token_impersonate': 'Token theft / impersonation',
    'dll_hijack': 'DLL search-order hijack',
    'named_pipe': 'Named pipe impersonation',
    'screen_capture': 'Screenshot / screen capture',
    'clipboard_monitor': 'Clipboard hijack/monitor',
    'audio_capture': 'Microphone/audio capture',
    'webcam_capture': 'Webcam capture',
    'botnet_irc': 'IRC botnet C2',
    'flood_stress': 'HTTP/UDP flood stress patterns',
    'spam_campaign': 'Bulk email/SMS spam campaign',
    'click_fraud': 'Click fraud / ad fraud automation',
    'install_script': 'Software installer / setup script',
    'config_file_only': 'Configuration or data file (low logic)',
    'idea_module_descriptor': 'IntelliJ IDEA module descriptor (.iml)',
    'maven_module_metadata': 'Maven/Java project module metadata',
    'python_marshal_payload': 'Python marshal/exec embedded bytecode stub',
    'unit_test_code': 'Unit test / test harness code',
    'build_script': 'Build/CI script (make, npm, gradle)',
    'doc_generator': 'Documentation generator',
    'data_etl': 'ETL / data processing pipeline',
}


def scan_extended_capabilities(text: str, *, filename: str = '') -> dict[str, list[str]]:
    """Return cap_id -> evidence strings for extended capability markers."""
    lower = text.lower()
    name = filename.lower()
    found: dict[str, list[str]] = {}

    def add(cap_id: str, evidence: str) -> None:
        found.setdefault(cap_id, [])
        if evidence not in found[cap_id]:
            found[cap_id].append(evidence[:160])

    patterns: list[tuple[str, str, str]] = [
        ('cobalt_strike', r'beacon\.|cobaltstrike|ReflectiveLoader|sleep\s*\(\s*\d+\s*\)\s*;', 'Cobalt Strike beacon pattern'),
        ('sliver_c2', r'sliver|armory\.|mtls\.|implant\s+generate', 'Sliver implant/C2'),
        ('havoc_c2', r'havoc|demon\s+agent|teamserver', 'Havoc C2'),
        ('asyncrat_marker', r'AsyncRAT|AsyncClient|ServerCertificate|GetAsyncKeyState', 'AsyncRAT'),
        ('njrat_marker', r'njRAT|Bladabindi|NJRat', 'NjRAT'),
        ('quasar_marker', r'Quasar\.Client|QuasarRAT|quasar\.exe', 'Quasar RAT'),
        ('remcos_marker', r'Remcos|remcos[\s_-]?rat|BreakWall', 'Remcos RAT'),
        ('redline_stealer', r'RedLine|RedLineStealer|redline[\s_-]?stealer', 'RedLine stealer'),
        ('impacket_tool', r'impacket|secretsdump|psexec\.py|wmiexec|smbexec|atexec', 'Impacket tooling'),
        ('bloodhound_ad', r'BloodHound|SharpHound|bloodhound\.py|Invoke-BloodHound', 'BloodHound AD'),
        ('mimikatz_tool', r'mimikatz|sekurlsa::|lsadump::|kerberos::', 'Mimikatz'),
        ('webshell_php', r'<\?php.*(?:eval|assert|system|passthru|shell_exec|base64_decode)', 'PHP webshell'),
        ('webshell_asp', r'<%.*eval\s*\(|Scripting\.FileSystemObject|cmd\.exe', 'ASP/JSP shell'),
        ('amsi_bypass', r'amsi\.dll|AmsiScanBuffer|amsiInitFailed|Bypass-AMSI', 'AMSI bypass'),
        ('uac_bypass', r'UAC\b|BypassUAC|fodhelper|eventvwr|sdclt', 'UAC bypass'),
        ('lolbin_certutil', r'certutil\s+-(?:decode|urlcache|encode)', 'Certutil LOLBin'),
        ('lolbin_msbuild', r'msbuild\.exe|Microsoft\.Build\.Tasks', 'MSBuild abuse'),
        ('lolbin_regsvr32', r'regsvr32\s+/s\s+/u\s+/i:', 'Regsvr32 squiblydoo'),
        ('lolbin_rundll32', r'rundll32\.exe\s+\S+,\s*(?:DllRegisterServer|Control_RunDLL)', 'Rundll32 abuse'),
        ('lolbin_mshta', r'mshta\.exe\s+(?:http|vbscript|javascript)', 'MSHTA remote'),
        ('macro_office', r'AutoOpen|Document_Open|Workbook_Open|AutoExec|VBA\.', 'Office macro'),
        ('hta_execution', r'\.hta["\']|<hta:|HTA:APPLICATION', 'HTA launcher'),
        ('crypto_miner', r'xmrig|minergate|cryptonight|monero|ethminer|nanopool', 'Crypto miner'),
        ('stratum_mining', r'stratum\+tcp|mining\.subscribe|mining\.authorize', 'Stratum mining'),
        ('browser_stealer', r'Login\s*Data|Web\s*Data|Chrome.*Profile|Firefox.*logins\.json', 'Browser data theft'),
        ('cookie_stealer', r'cookie|sessionid|document\.cookie', 'Cookie theft'),
        ('discord_stealer', r'discord.*token|Local\s*Storage.*discord|mfa\.', 'Discord token'),
        ('wallet_stealer', r'wallet\.dat|MetaMask|exodus|atomicwallet|seed\s*phrase', 'Crypto wallet'),
        ('password_spray', r'password\s*spray|Spray-Password|try_password|userlist.*passlist', 'Password spray'),
        ('ssh_brute', r'ssh\.connect|paramiko.*password|hydra.*ssh|bruteforce.*ssh', 'SSH brute'),
        ('kerberos_attack', r'kerberoast|asreproast|golden\s*ticket|silver\s*ticket|rubeus', 'Kerberos attack'),
        ('ldap_enumeration', r'ldapsearch|Get-ADUser|Get-ADGroup|bloodhound|ldap\.', 'LDAP/AD enum'),
        ('dcom_lateral', r'DCOM|MMC20\.Application|ShellBrowserWindow', 'DCOM lateral'),
        ('wmi_lateral', r'Invoke-WmiMethod|win32_process|wmic\s+/node', 'WMI lateral'),
        ('psexec_lateral', r'psexec|PaExec|RemCom|winexe\s', 'PsExec lateral'),
        ('sandbox_evasion', r'sleep\s*\(\s*[5-9]\d{3,}|IsDebuggerPresent|CheckRemoteDebugger', 'Sandbox evasion'),
        ('vm_detection', r'VBoxGuest|VMware|vboxservice|qemu|Xen', 'VM detection'),
        ('dns_exfil', r'dns\.resolve|TXT\s+record|iodine|dnscat', 'DNS exfil'),
        ('icmp_tunnel', r'icmpsh|icmp.*tunnel|ping\s+-p', 'ICMP tunnel'),
        ('tor_network', r'tor2web|\.onion|socks5://127\.0\.0\.1:9050', 'Tor network'),
        ('proxy_socks', r'socks5|SOCKS4|proxychains|reGeorg', 'SOCKS proxy'),
        ('phishing_html', r'login\.php|signin.*password|credential.*form|phish', 'Phishing HTML'),
        ('sql_injection', r"'\s*OR\s*'1'='1|UNION\s+SELECT|sqlmap|sql\s*injection", 'SQLi probe'),
        ('xss_probe', r'<script>|onerror=|javascript:|alert\s*\(\s*document', 'XSS probe'),
        ('container_escape', r'docker\.sock|/var/run/docker|kubelet|privileged:\s*true', 'Container escape'),
        ('kube_exfil', r'kubernetes|kubectl|/api/v1/namespaces|serviceaccount', 'Kubernetes API'),
        ('aws_exfil', r'169\.254\.169\.254|aws_access_key|boto3\.client|metadata\.google', 'Cloud metadata/AWS'),
        ('azure_exfil', r'azure\.com|DefaultAzureCredential|IMDS', 'Azure abuse'),
        ('gcp_exfil', r'googleapis\.com.*metadata|gcloud\s+auth', 'GCP abuse'),
        ('ransomware_vss', r'vssadmin\s+delete\s+shadows|wbadmin\s+delete|bcdedit\s+/set', 'VSS deletion'),
        ('reflective_dll', r'ReflectiveLoader|ReflectiveDLL|LoadLibrary.*remote', 'Reflective DLL'),
        ('donut_loader', r'donut|DonutLoader|Module\.Overloading', 'Donut loader'),
        ('nuclei_scanner', r'nuclei\s+-t|projectdiscovery/nuclei', 'Nuclei scanner'),
        ('ffuf_fuzzer', r'ffuf\s+|gobuster\s+|dirb\s+|feroxbuster', 'Web fuzzer'),
        ('hydra_brute', r'hydra\s+-|THC-Hydra|medusa\s+-', 'Hydra brute'),
        ('hashcat_helper', r'hashcat\s+-|john\s+--wordlist|hash\s*crack', 'Hash cracking'),
        ('responder_poison', r'Responder|LLMNR|NBT-NS|Poisoner', 'Responder poison'),
        ('bettercap_attack', r'bettercap|arp\.spoof|net\.sniff', 'Bettercap MITM'),
        ('sqlmap_tool', r'sqlmap\s+|--batch\s+--dump', 'SQLMap'),
        ('beef_hook', r'beef\.hook|BeEF|browser\s*exploitation', 'BeEF hook'),
        ('empire_agent', r'PowerShell\s*Empire|stager\s+uri|Invoke-Empire', 'PS Empire'),
        ('covenant_grpc', r'Covenant\.|GruntHTTP|CovenantAPI', 'Covenant C2'),
        ('persistence_wmi', r'__EventFilter|__EventConsumer|Subscription', 'WMI persistence'),
        ('persistence_schtask', r'schtasks\s+/create|Register-ScheduledTask', 'Scheduled task persist'),
        ('persistence_startup', r'Startup\\|shell:startup|/etc/rc\.local', 'Startup persistence'),
        ('defense_disable', r'DisableAntiSpyware|DisableRealtimeMonitoring|Set-MpPreference\s+-Disable', 'Disable defenses'),
        ('log_clearing', r'wevtutil\s+cl|Clear-EventLog|EventLog.*Clear', 'Log clearing'),
        ('timestomp', r'timestomp|Set-MacAttribute|touch\s+-t', 'Timestomp'),
        ('process_hollow', r'NtUnmapViewOfSection|process\s*hollow|RunPE', 'Process hollowing'),
        ('api_unhook', r'NtProtectVirtualMemory.*ntdll|unhook|FreshCopy', 'API unhook'),
        ('token_impersonate', r'ImpersonateLoggedOnUser|DuplicateToken|Incognito', 'Token impersonation'),
        ('dll_hijack', r'DLL\s*hijack|phantom\s+dll|SearchOrder', 'DLL hijack'),
        ('named_pipe', r'\\\\\.\\pipe\\|CreateNamedPipe|PrintSpoofer', 'Named pipe abuse'),
        ('screen_capture', r'ImageGrab|screenshot|BitBlt|mss\.mss', 'Screen capture'),
        ('clipboard_monitor', r'clipboard|GetClipboardData|pyperclip', 'Clipboard monitor'),
        ('audio_capture', r'pyaudio|sounddevice|microphone|waveInOpen', 'Audio capture'),
        ('webcam_capture', r'VideoCapture|cv2\.VideoCapture|webcam', 'Webcam capture'),
        ('botnet_irc', r'IRC\s*bot|PRIVMSG.*!|JOIN\s+#', 'IRC botnet'),
        ('flood_stress', r'UDP\s*flood|HTTP\s*flood|slowloris|LOIC|HOIC', 'Flood/stress'),
        ('spam_campaign', r'bulk\s*mail|mass\s*email|smtp.*loop|mail\s*bomb', 'Spam campaign'),
        ('click_fraud', r'click\s*fraud|ad\s*click|bot\s*traffic', 'Click fraud'),
        ('install_script', r'install\s*script|setup\.py|npm\s+install|pip\s+install', 'Installer script'),
        ('unit_test_code', r'unittest|pytest|describe\s*\(|assert\s+Equal|@Test', 'Unit tests'),
        ('build_script', r'cmake|makefile|gradle|webpack|npm\s+run\s+build', 'Build/CI script'),
        ('doc_generator', r'sphinx|mkdocs|doxygen|javadoc', 'Doc generator'),
        ('data_etl', r'pandas\.read_|spark\.read|ETL|extract.*transform.*load', 'Data ETL'),
    ]

    for cap_id, pattern, evidence in patterns:
        if re.search(pattern, text, re.I | re.S):
            add(cap_id, evidence)

    if name.endswith(('.php', '.phtml')) and re.search(r'eval|system|shell_exec', lower):
        add('webshell_php', 'PHP extension + exec primitive')
    if name.endswith(('.hta',)):
        add('hta_execution', 'HTA file extension')

    return found
